version: '2.4'
services:
    autobu:
        hostname: obu
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=6
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:      
            kernel.msgmax:  16384

    carobu:
        hostname: obu
        image: vanetza:test
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=eth0
            - START_EMBEDDED_MOSQUITTO=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:      
            kernel.msgmax:  16384
            
    react:
        hostname: react
        image: vanetza:react
        build: ./react-app
        depends_on:
        - autobu
        - carobu
        volumes: 
        - '.:/app'
        - '/app/node_modules'
        ports:
        - "3000:3000"
        environment:
        - CHOKIDAR_USEPOLLING=true
            
networks:
  vanetzalan0:
    external: true
    name: vanetzalan0