version: '2.4'
services:
    autobu:
        hostname: obu
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=6
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - VANETZA_CAM_PERIODICITY=0
            - START_EMBEDDED_MOSQUITTO=true
            - EMBEDDED_MOSQUITTO_PORT=1883
            - VANETZA_MQTT_PORT=1883
            - VANETZA_PROMETHEUS_PORT=4000
            - SUPPORT_MAC_BLOCKING=true
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    carobu:
        hostname: obu
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - VANETZA_CAM_PERIODICITY=0
            - START_EMBEDDED_MOSQUITTO=true
            - EMBEDDED_MOSQUITTO_PORT=1884
            - VANETZA_MQTT_PORT=1884
            - VANETZA_PROMETHEUS_PORT=4001
            - SUPPORT_MAC_BLOCKING=true
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    react:
        hostname: react
        image: vanetza:react
        build: ./react-app
        depends_on:
        - autobu
        - carobu
        volumes:
        - '.:/app'
        - '/app/node_modules'
        ports:
        - "3000:80"
        environment:
        - CHOKIDAR_USEPOLLING=true
             
networks:
  vanetzalan0:
    external: true
    name: vanetzalan0
